services:
  web:
    container_name: web
    build:
      context: .
      dockerfile: ./apps/web/Dockerfile
    restart: always
    ports:
      - 3000:3000
    environment:
      - NODE_ENV=production
      - NEXT_PUBLIC_API_URL=https://prep.uteq.edu.mx/api
    depends_on:
      - api
    networks:
      - app_network

  api:
    container_name: api
    build:
      context: .
      dockerfile: ./apps/api/Dockerfile
    restart: always
    ports:
      - 3001:3001
    env_file:
      - ./apps/api/.env.production
    depends_on:
      - mongodb
    networks:
      - app_network

  mongodb:
    container_name: mongodb
    image: mongo:6
    restart: always
    ports:
      - 27017:27017
    command: ['mongod', '--replSet', 'rs0', '--bind_ip_all']
    # Disabe authentication for dev (enable for production)
    # environment:
    #   - MONGO_INITDB_ROOT_USERNAME=user
    #   - MONGO_INITDB_ROOT_PASSWORD=pass
    volumes:
      - mongodb_data:/data/db
    networks:
      - app_network
    healthcheck:
      test: echo "try { rs.status() } catch (err) { rs.initiate({_id:'rs0',members:[{_id:0,host:'mongodb:27017'}]}) }" | mongosh --port 27017 --quiet
      interval: 10s
      timeout: 30s
      retries: 5

networks:
  app_network:
    driver: bridge

volumes:
  mongodb_data:
    driver: local
