export enum FilePurpose {
  GENERIC = 'GENERIC',
  EVENT_FINANCIAL_REPORT = 'EVENT_FINANCIAL_REPORT',
  EVENT_TECHNICAL_REPORT = 'EVENT_TECHNICAL_REPORT',
  EVENT_EVIDENCE = 'EVENT_EVIDENCE',
  EVENT_OTHER = 'EVENT_OTHER',
  PROJECT_FINANCIAL_REPORT = "PROJECT_FINANCIAL_REPORT",
}
