# -------------------------
# Base Stage
# -------------------------
FROM node:20-alpine AS base
RUN apk update && apk add --no-cache libc6-compat bash
RUN corepack enable && corepack prepare pnpm@9.0.0 --activate
ENV PNPM_HOME="/pnpm"
ENV PATH="$PNPM_HOME:$PATH"

WORKDIR /app

# -------------------------
# Install dependencies
# -------------------------
COPY package.json pnpm-workspace.yaml pnpm-lock.yaml ./
# Copy shared packages
COPY packages ./packages
# Copy source code
COPY apps/api ./apps/api

RUN pnpm install

WORKDIR /app/apps/api

# -------------------------
# Expose port
# -------------------------
EXPOSE 3001

# -------------------------
# Command for development
# -------------------------
CMD ["pnpm", "dev"]
