# -------------------------
# Base Stage
# -------------------------
FROM node:20-alpine
RUN apk update && apk add --no-cache libc6-compat bash
RUN corepack enable && corepack prepare pnpm@9.0.0 --activate

WORKDIR /app

# -------------------------
# Install dependencies
# -------------------------
COPY package.json pnpm-workspace.yaml pnpm-lock.yaml ./
COPY packages ./packages
COPY apps/api ./apps/api

RUN pnpm install

# -------------------------
# Expose port
# -------------------------
EXPOSE 3001

# -------------------------
# Run Nest from app root
# -------------------------
WORKDIR /app/apps/api
CMD ["pnpm", "dev"]
