name: Deployment Pipeline

on:
  push:
    branches:
      - feature/setup-deployment

jobs:
  deploy:
    runs-on: self-hosted
    steps:
      - name: Echo the message
        run: echo 'Running on github-runner service'
